
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: xjt199384

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.peach.springboot.bean

